version: '3.8'

services:
  app:
    build: .
    container_name: appnotas-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_NAME=appnotas_db
      - PORT=3000
    depends_on:
      - db
    volumes:
      # Útil para desarrollo: montar el código local en el contenedor
      - ./src:/usr/src/app/src
      - ./frontend:/usr/src/app/frontend

  db:
    image: postgres:15-alpine
    container_name: appnotas-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=appnotas_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
